server:
  port: 8081

spring:
  application:
    name: account-service      # this becomes the ID in Eureka (ACCOUNT-SERVICE)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # where to register
  instance:
    prefer-ip-address: true
